# tb-profiler error report

* OS: linux
* Program version: 4.2.0
* Program call:
```
{'prefix': 'tbdb', 'csv': 'tbdb.csv', 'watchlist': 'tbdb.watchlist.csv', 'spoligotypes': 'spoligotype_spacers.txt', 'barcode': 'barcode.bed', 'amplicon_primers': None, 'match_ref': None, 'other_annotations': 'tbdb.other_annotations.csv', 'custom': False, 'db_name': None, 'db_commit': None, 'db_author': None, 'db_date': None, 'include_original_mutation': False, 'load': False, 'dir': '.', 'no_clean': False, 'func': <function main_create_db at 0x7ff022d6f9d0>, 'software_name': 'tbprofiler', 'tmp_prefix': '0d99fa81-0749-41f1-9c74-1e4e0f7e391a', 'files_prefix': './0d99fa81-0749-41f1-9c74-1e4e0f7e391a'}
```
## Traceback:
```
  File "/home/khhor/conda/envs/tbp2/bin/tb-profiler", line 566, in <module>
    args.func(args)
  File "/home/khhor/conda/envs/tbp2/bin/tb-profiler", line 210, in main_create_db
    pp.create_db(args,extra_files=extra_files)
  File "/home/khhor/dev/pathogen-profiler/pathogenprofiler/db.py", line 556, in create_db
    mutation_lookup = get_snpeff_formated_mutation_list(args.csv,"genome.fasta","genome.gff",json.load(open("variables.json"))["snpEff_db"])
  File "/home/khhor/dev/pathogen-profiler/pathogenprofiler/db.py", line 193, in get_snpeff_formated_mutation_list
    for row in csv.DictReader(open(csv_file)):
```
## Value:
```
[Errno 2] No such file or directory: 'tbdb.csv'```
